In [499]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [500]:
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros = np.array(lista_de_centimetros)

In [501]:
altura_em_metros = lista_de_centimetros / 100
print(altura_em_metros)

[1.7  1.75 1.8  1.85]


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [502]:
lista_pesos = [70, 75, 80, 85]
lista_pesos = np.array(lista_pesos)

# seu código aqui

def imc(lista_pesos, altura_em_metros):
    return np.round(lista_pesos / (altura_em_metros ** 2), 2)

In [503]:
# calcule o IMC dessas pessoas

print(imc(lista_pesos, altura_em_metros))

[24.22 24.49 24.69 24.84]


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [504]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
dados_financeiros = np.array(dados_financeiros)
#i) transforme essa lista em um ndarray

In [505]:
# ii) 
nd_financeiros = np.transpose(dados_financeiros)
print(f'Lista filtrada para melhor entendimento.')
print(nd_financeiros[0], "|", nd_financeiros[1], "|", nd_financeiros[2], "|", nd_financeiros[3])

Lista filtrada para melhor entendimento.
[3000 1000 6000] | [2500 2500 5500] | [1000 3000 7000] | [10000  5000 16000]


In [506]:
# iii) Calcule o endividamento total
def endividamento_total(nd_financeiros):
    return np.round(nd_financeiros[:, 0] + nd_financeiros[:, 1] / nd_financeiros[:, 2], 2)
endividamento_total(nd_financeiros)

array([ 3000.17,  2500.45,  1000.43, 10000.31])

In [507]:
# iv) corrigindo um valor específico
nd_financeiros[2, 2] = 10000
endividamento_total(nd_financeiros)

array([ 3000.17,  2500.45,  1000.3 , 10000.31])

In [508]:
# Valor não corrigo o resultado fica alterado na posição 3 sob o número dois de 13 centavos em relação ao valor correto.
nd_financeiros[2, 2] = 7000
endividamento_total(nd_financeiros)

array([ 3000.17,  2500.45,  1000.43, 10000.31])

### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [509]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [510]:
# i) crie o objeto bool_zero através do operador ==
bool_zero = poi == 0

In [511]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)
sum(bool_zero)

6

In [512]:
# iii) utilize a indexação booleana para criar uma seleção de não-zeros
non_zero_poi = poi[poi != 0]
# dica: inverta o objeto bool_zero
poi[poi == 0] = 1

In [513]:
# saídas
print(f'poi: {poi}')
print(f'bool_zero: {bool_zero}')
print(f'non_zero_poi: {non_zero_poi}')

poi: [3 3 6 2 4 5 4 4 2 1 3 3 2 8 2 3 3 3 1 4 4 2 6 6 1 3 4 3 5 2 1 3 2 2 3 2 4
 4 5 7 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 1 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4
 1 1 7 1 2 1 3 7 1 4 4 1 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
bool_zero: [False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]
non_zero_poi: [3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3